### ISSUE TITLE
metrics server can't be opened via curl or wget.

### ISSUE THREAD

**Issue by kotenok2000** [loda-lang/loda-rust#20]
When i run "curl  -v http://localhost:8090/metrics" or  "curl -v http://192,168.1.7:8090/metrics" from other device in LAN i get a timeout.

**Comment by neoneye** [comment]
What platform are you on?

What do you see when starting the miner?

What does the curl command output?

I don't have any Windows computer, so I may not be able to fix it.

On macOS 12.6. The miner is started like this:
![metrics1](https://user-images.githubusercontent.com/147971/193142058-394b11e6-9531-41b3-947b-d1a8a8356a5f.jpeg)

When I run the same curl command as you, there seems to be a minor issue with ipv6 localhost.
![metrics2](https://user-images.githubusercontent.com/147971/193143510-434183a5-75f5-482a-8774-b98a1cb8bcf7.jpeg)

**Comment by kotenok2000** [comment]
I have made a symlink from ~/git/loda-rust/loda-rust to /home/user/git/loda-rust/rust_project/target/release/loda-rust


 loda-rust mine --metrics
metrics mode: RunMetricsServer
Number of workers: 8
[mining info]
build_mode = 'RELEASE'  # Good
number of .asm files in mine_event_dir: 0
number of .asm files in oeis_divergent_dir: 19181
number of .asm files in total: 19181
████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 12874/19181█████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 12953/19181    Finished prevent_flooding_populate in 11 seconds
number of programs added to the PreventFlooding mechanism: 8898
miner metrics can be downloaded here: http://localhost:8090/metrics
Spawn worker id: 0

**Comment by kotenok2000** [comment]
Foe some reason it started working

**Comment by neoneye** [comment]
I have not written any guide for how to install Prometheus, and Grafana.

You should be able to use [these config files](https://github.com/loda-lang/loda-rust/tree/develop/resources/realtime%20metrics). Please let me know you encounter issues with it.

This is what the dashboard looks like
![Screen Shot 2022-09-29 at 23 46 56](https://user-images.githubusercontent.com/147971/193148076-ce237a00-81cc-459b-8cf5-69315b5c0116.jpg)
