### ISSUE TITLE
Loda-rust will fail to compile in future rust versions.

### ISSUE THREAD

**Issue by kotenok2000** [loda-lang/loda-rust#29]
It shows warning in cargo 1.70.0 (ec8a8a0ca 2023-04-25) and already doesn't work in nightly version

![image](https://github.com/loda-lang/loda-rust/assets/8822292/e1236e29-cc5f-4c0f-8b42-40ba55451f8e)

**Comment by neoneye** [comment]
I will fix it. Thanks for reporting it.

The `linfa` project has [this issue](https://github.com/rust-ml/linfa/issues/303) that about the dependency on `argmin`.

**Comment by neoneye** [comment]
I have now fixed it. 

Let me know if it doesn't work.
