### ISSUE TITLE
Several programs crashed loda.exe when evaluated by loda-cpp.

### ISSUE THREAD

**Issue by kotenok2000** [loda-lang/loda-rust#30]
It generates lots of crash dumps 0.5 mb each.

They all have uncommented commentaries like 

; template 283770
; mutate: CallMostPopularProgram
; keep: maybe a new program. cannot compute program 175088 with the same initial terms. error: run_result error in program.run

Caused by:
    Step count exceeded limit, using way too many cpu cycles

; reject-reason: Couldn't eval program with loda-cpp, Expected exit_code: 0, but got exit_code: Some(-1073740791), loda_program_path: "C:\\Users\\frolo\\.loda-rust\\mine-event\\20230712-130406-38216.asm"
; stdout: 
; stderr: 
; 
; Caused by:
;     Non-zero exit code
[mine-event.zip](https://github.com/loda-lang/loda-rust/files/12028274/mine-event.zip)

**Comment by neoneye** [comment]
Can you attach another zip file?

I can't unzip the zip file. The zip file is 8169 bytes, so it's tiny.

**Comment by kotenok2000** [comment]
-1073740791
Zip opens fine in 7-zip
I have recreated it via winrar
[mine-event.zip](https://github.com/loda-lang/loda-rust/files/12029483/mine-event.zip)
It has 11 files 10.9 KiB uncompressed.

**Comment by neoneye** [comment]
the zip file unzips fine now.

It seems that the error messages needs a semicolon at the beginning of the error messages. I will add that asap.

**Comment by neoneye** [comment]
Can you check if it works now?

I have added the missing semicolons, see this commit: https://github.com/loda-lang/loda-rust/commit/a4d9fd5556b4829696ad08f493d7ba1c0a2471d6

**Comment by kotenok2000** [comment]
It doesn't crash now.
