### ISSUE TITLE
Assertion failed 'assertion failed: path.is_dir()', loda-rust-cli\src\config\config.rs:193:9 when using "C:/Users/frolo/loda/programs/patterns/" as patterns directory instead of "E:/git/loda-patterns"

### ISSUE THREAD

**Issue by kotenok2000** [loda-lang/loda-rust#31]
It happens when i run loda-rust pattern

**Comment by neoneye** [comment]
Try create this dir the `C:/Users/frolo/loda/programs/patterns/simple_constant` dir, where the dirname is `simple_constant`.

Ideally the `loda-rust pattern` subcommand should create all the dirs needed. PR is welcome.

**Comment by kotenok2000** [comment]
I created C:/Users/frolo/loda/programs/patterns/simple_constant

now it fails with  [2023-07-17T19:58:03Z ERROR loda_rust::subcommand_pattern] Expected 1 or more similarity csv files, but there are none to analyze

**Comment by neoneye** [comment]
If you do this:
1. copy all the content from `"E:/git/loda-patterns"` to `"C:/Users/frolo/loda/programs/patterns/"`.
2. run `loda-rust pattern`

Does this work?
